import { MinistryProgram } from './types';

export const MINISTRY_PROGRAMS: Record<string, MinistryProgram[]> = {
  defence: [
    { id: 'd1', name: 'Border Security Upgrade', description: 'Deploy advanced surveillance along borders', budget_required: 5000, success_rate: 0.75, morale_impact: 5, efficiency_gain: 8, execution_month: 0, status: 'pending' },
    { id: 'd2', name: 'Soldier Training Program', description: 'Enhance combat readiness', budget_required: 3000, success_rate: 0.8, morale_impact: 10, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'd3', name: 'Missile Tech Development', description: 'Research advanced missile systems', budget_required: 8000, success_rate: 0.6, morale_impact: 3, efficiency_gain: 15, execution_month: 4, status: 'pending' },
    { id: 'd4', name: 'Coastal Defense Initiative', description: 'Strengthen naval surveillance', budget_required: 6000, success_rate: 0.7, morale_impact: 4, efficiency_gain: 7, execution_month: 3, status: 'pending' },
    { id: 'd5', name: 'Cyber Warfare Unit', description: 'Establish cybersecurity teams', budget_required: 4000, success_rate: 0.65, morale_impact: 6, efficiency_gain: 12, execution_month: 1, status: 'pending' },
    { id: 'd6', name: 'Military Hospital Expansion', description: 'Upgrade healthcare for soldiers', budget_required: 2500, success_rate: 0.85, morale_impact: 8, efficiency_gain: 5, execution_month: 2, status: 'pending' },
  ],
  education: [
    { id: 'e1', name: 'Digital Learning Initiative', description: 'Deploy online education platforms', budget_required: 4000, success_rate: 0.7, morale_impact: 7, efficiency_gain: 10, execution_month: 1, status: 'pending' },
    { id: 'e2', name: 'Teacher Training Program', description: 'Upskill 100K teachers', budget_required: 3000, success_rate: 0.75, morale_impact: 6, efficiency_gain: 8, execution_month: 3, status: 'pending' },
    { id: 'e3', name: 'School Infrastructure', description: 'Build 5000 new schools', budget_required: 10000, success_rate: 0.55, morale_impact: 5, efficiency_gain: 12, execution_month: 6, status: 'pending' },
    { id: 'e4', name: 'STEM Education Program', description: 'Promote science/tech education', budget_required: 5000, success_rate: 0.68, morale_impact: 4, efficiency_gain: 14, execution_month: 2, status: 'pending' },
    { id: 'e5', name: 'Scholarship Expansion', description: 'Provide scholarships to 50K students', budget_required: 2000, success_rate: 0.82, morale_impact: 9, efficiency_gain: 3, execution_month: 0, status: 'pending' },
    { id: 'e6', name: 'University Research Labs', description: 'Establish research facilities', budget_required: 7000, success_rate: 0.62, morale_impact: 5, efficiency_gain: 16, execution_month: 5, status: 'pending' },
  ],
  health: [
    { id: 'h1', name: 'COVID Vaccination Drive', description: 'Vaccinate 500M people', budget_required: 6000, success_rate: 0.72, morale_impact: 8, efficiency_gain: 9, execution_month: 1, status: 'pending' },
    { id: 'h2', name: 'Rural Clinic Network', description: 'Open 2000 rural clinics', budget_required: 5000, success_rate: 0.65, morale_impact: 7, efficiency_gain: 11, execution_month: 4, status: 'pending' },
    { id: 'h3', name: 'Medical Equipment Upgrade', description: 'Buy ventilators and ECG machines', budget_required: 4000, success_rate: 0.75, morale_impact: 5, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'h4', name: 'Ayurveda Modernization', description: 'Research traditional + modern medicine', budget_required: 3000, success_rate: 0.58, morale_impact: 4, efficiency_gain: 10, execution_month: 3, status: 'pending' },
    { id: 'h5', name: 'Maternal Health Program', description: 'Reduce maternal mortality', budget_required: 2500, success_rate: 0.78, morale_impact: 6, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'h6', name: 'Disease Surveillance System', description: 'Real-time disease tracking', budget_required: 3500, success_rate: 0.7, morale_impact: 3, efficiency_gain: 12, execution_month: 2, status: 'pending' },
  ],
  finance: [
    { id: 'f1', name: 'GST Implementation', description: 'Streamline tax collection', budget_required: 2000, success_rate: 0.8, morale_impact: -5, efficiency_gain: 20, execution_month: 0, status: 'pending' },
    { id: 'f2', name: 'Digital Rupee Launch', description: 'Develop CBDC platform', budget_required: 3000, success_rate: 0.65, morale_impact: 2, efficiency_gain: 18, execution_month: 3, status: 'pending' },
    { id: 'f3', name: 'Banking Sector Reform', description: 'Strengthen RBI oversight', budget_required: 1500, success_rate: 0.75, morale_impact: 1, efficiency_gain: 10, execution_month: 1, status: 'pending' },
    { id: 'f4', name: 'Forex Reserve Growth', description: 'Boost international reserves', budget_required: 4000, success_rate: 0.72, morale_impact: 3, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'f5', name: 'Inflation Control', description: 'Manage price stability', budget_required: 1000, success_rate: 0.6, morale_impact: 4, efficiency_gain: 15, execution_month: 1, status: 'pending' },
    { id: 'f6', name: 'Securities Regulation', description: 'Strengthen market oversight', budget_required: 2000, success_rate: 0.77, morale_impact: 2, efficiency_gain: 9, execution_month: 2, status: 'pending' },
  ],
  commerce: [
    { id: 'c1', name: 'Export Promotion Scheme', description: 'Support 5K exporters', budget_required: 3000, success_rate: 0.68, morale_impact: 6, efficiency_gain: 14, execution_month: 1, status: 'pending' },
    { id: 'c2', name: 'Trade Deal Negotiation', description: 'Secure bilateral agreements', budget_required: 500, success_rate: 0.62, morale_impact: 4, efficiency_gain: 20, execution_month: 2, status: 'pending' },
    { id: 'c3', name: 'Startup Ecosystem', description: 'Support 100 startups', budget_required: 2000, success_rate: 0.72, morale_impact: 7, efficiency_gain: 13, execution_month: 1, status: 'pending' },
    { id: 'c4', name: 'Supply Chain Reform', description: 'Modernize logistics', budget_required: 4000, success_rate: 0.58, morale_impact: 3, efficiency_gain: 16, execution_month: 4, status: 'pending' },
    { id: 'c5', name: 'IP Protection Law', description: 'Strengthen patent system', budget_required: 1000, success_rate: 0.75, morale_impact: 2, efficiency_gain: 11, execution_month: 2, status: 'pending' },
    { id: 'c6', name: 'Consumer Protection', description: 'Enhance quality standards', budget_required: 1500, success_rate: 0.7, morale_impact: 5, efficiency_gain: 8, execution_month: 1, status: 'pending' },
  ],
  it: [
    { id: 'i1', name: 'AI Research Hub', description: 'Establish AI institutes', budget_required: 5000, success_rate: 0.6, morale_impact: 4, efficiency_gain: 20, execution_month: 3, status: 'pending' },
    { id: 'i2', name: '5G Rollout', description: 'Deploy 5G infrastructure', budget_required: 8000, success_rate: 0.55, morale_impact: 6, efficiency_gain: 18, execution_month: 5, status: 'pending' },
    { id: 'i3', name: 'Cybersecurity Policy', description: 'Create data protection laws', budget_required: 2000, success_rate: 0.72, morale_impact: 3, efficiency_gain: 14, execution_month: 2, status: 'pending' },
    { id: 'i4', name: 'Semiconductor Plant', description: 'Build chip manufacturing', budget_required: 10000, success_rate: 0.45, morale_impact: 5, efficiency_gain: 25, execution_month: 8, status: 'pending' },
    { id: 'i5', name: 'IT Services Export', description: 'Boost software exports', budget_required: 1500, success_rate: 0.78, morale_impact: 6, efficiency_gain: 12, execution_month: 1, status: 'pending' },
    { id: 'i6', name: 'Green Data Centers', description: 'Build eco-friendly data centers', budget_required: 6000, success_rate: 0.65, morale_impact: 4, efficiency_gain: 13, execution_month: 3, status: 'pending' },
  ],
  power: [
    { id: 'p1', name: 'Solar Farm Expansion', description: 'Add 100GW solar capacity', budget_required: 7000, success_rate: 0.68, morale_impact: 5, efficiency_gain: 16, execution_month: 4, status: 'pending' },
    { id: 'p2', name: 'Grid Modernization', description: 'Upgrade transmission lines', budget_required: 5000, success_rate: 0.72, morale_impact: 3, efficiency_gain: 14, execution_month: 3, status: 'pending' },
    { id: 'p3', name: 'Coal Plant Phaseout', description: 'Retire old coal plants', budget_required: 3000, success_rate: 0.58, morale_impact: -3, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'p4', name: 'Wind Energy Initiative', description: 'Add 50GW wind capacity', budget_required: 6000, success_rate: 0.65, morale_impact: 4, efficiency_gain: 13, execution_month: 4, status: 'pending' },
    { id: 'p5', name: 'Battery Storage System', description: 'Build energy storage facilities', budget_required: 4000, success_rate: 0.62, morale_impact: 3, efficiency_gain: 15, execution_month: 3, status: 'pending' },
    { id: 'p6', name: 'Household Solar Program', description: 'Install 10M rooftop systems', budget_required: 3000, success_rate: 0.7, morale_impact: 7, efficiency_gain: 9, execution_month: 2, status: 'pending' },
  ],
  water: [
    { id: 'w1', name: 'Water Treatment Plants', description: 'Build 500 treatment plants', budget_required: 4000, success_rate: 0.65, morale_impact: 8, efficiency_gain: 11, execution_month: 4, status: 'pending' },
    { id: 'w2', name: 'Groundwater Recharge', description: 'Implement rainwater harvesting', budget_required: 2000, success_rate: 0.7, morale_impact: 6, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'w3', name: 'River Cleanup Drive', description: 'Clean 15 major rivers', budget_required: 3000, success_rate: 0.55, morale_impact: 5, efficiency_gain: 9, execution_month: 3, status: 'pending' },
    { id: 'w4', name: 'Sewage Management', description: 'Upgrade sewage systems in 100 cities', budget_required: 5000, success_rate: 0.6, morale_impact: 4, efficiency_gain: 10, execution_month: 4, status: 'pending' },
    { id: 'w5', name: 'Dam Safety Audit', description: 'Inspect all major dams', budget_required: 1500, success_rate: 0.75, morale_impact: 2, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 'w6', name: 'Desalination Plants', description: 'Build 10 coastal plants', budget_required: 6000, success_rate: 0.58, morale_impact: 3, efficiency_gain: 12, execution_month: 5, status: 'pending' },
  ],
  railways: [
    { id: 'r1', name: 'High-Speed Rail', description: 'Build bullet train routes', budget_required: 8000, success_rate: 0.52, morale_impact: 6, efficiency_gain: 18, execution_month: 6, status: 'pending' },
    { id: 'r2', name: 'Station Modernization', description: 'Upgrade 500 railway stations', budget_required: 4000, success_rate: 0.68, morale_impact: 5, efficiency_gain: 10, execution_month: 3, status: 'pending' },
    { id: 'r3', name: 'Freight Corridor', description: 'Build dedicated freight lines', budget_required: 5000, success_rate: 0.62, morale_impact: 2, efficiency_gain: 14, execution_month: 4, status: 'pending' },
    { id: 'r4', name: 'Safety Enhancement', description: 'Install automatic braking', budget_required: 3000, success_rate: 0.72, morale_impact: 4, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'r5', name: 'Electrification Drive', description: 'Electrify all remaining routes', budget_required: 4000, success_rate: 0.65, morale_impact: 3, efficiency_gain: 11, execution_month: 3, status: 'pending' },
    { id: 'r6', name: 'Passenger Comfort', description: 'Improve onboard amenities', budget_required: 2000, success_rate: 0.8, morale_impact: 7, efficiency_gain: 5, execution_month: 1, status: 'pending' },
  ],
  roads: [
    { id: 'rd1', name: 'National Highway Expansion', description: 'Build 10K km highways', budget_required: 7000, success_rate: 0.6, morale_impact: 4, efficiency_gain: 14, execution_month: 5, status: 'pending' },
    { id: 'rd2', name: 'Metro Rail Projects', description: 'Build metros in 20 cities', budget_required: 6000, success_rate: 0.55, morale_impact: 6, efficiency_gain: 12, execution_month: 4, status: 'pending' },
    { id: 'rd3', name: 'Road Safety Initiative', description: 'Install safety systems', budget_required: 2000, success_rate: 0.73, morale_impact: 3, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'rd4', name: 'EV Charging Network', description: 'Install 100K charging stations', budget_required: 4000, success_rate: 0.62, morale_impact: 5, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'rd5', name: 'Bridge Repair Program', description: 'Repair aging bridges', budget_required: 3000, success_rate: 0.68, morale_impact: 2, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'rd6', name: 'Smart Traffic System', description: 'Deploy AI traffic management', budget_required: 2500, success_rate: 0.7, morale_impact: 4, efficiency_gain: 10, execution_month: 2, status: 'pending' },
  ],
  aviation: [
    { id: 'av1', name: 'Airport Expansion', description: 'Upgrade 50 airports', budget_required: 5000, success_rate: 0.65, morale_impact: 4, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'av2', name: 'Air Safety Standards', description: 'Implement ICAO guidelines', budget_required: 2000, success_rate: 0.78, morale_impact: 2, efficiency_gain: 8, execution_month: 1, status: 'pending' },
    { id: 'av3', name: 'Drone Regulation', description: 'Establish drone airspace rules', budget_required: 1000, success_rate: 0.72, morale_impact: 1, efficiency_gain: 9, execution_month: 1, status: 'pending' },
    { id: 'av4', name: 'Flight Training Program', description: 'Train 1000 pilots', budget_required: 2500, success_rate: 0.7, morale_impact: 5, efficiency_gain: 7, execution_month: 2, status: 'pending' },
    { id: 'av5', name: 'Cargo Network Expansion', description: 'Boost cargo operations', budget_required: 2000, success_rate: 0.68, morale_impact: 3, efficiency_gain: 11, execution_month: 2, status: 'pending' },
    { id: 'av6', name: 'Electric Aviation', description: 'Develop electric aircraft', budget_required: 4000, success_rate: 0.5, morale_impact: 4, efficiency_gain: 16, execution_month: 4, status: 'pending' },
  ],
  shipping: [
    { id: 's1', name: 'Port Infrastructure', description: 'Upgrade major ports', budget_required: 4000, success_rate: 0.62, morale_impact: 3, efficiency_gain: 13, execution_month: 3, status: 'pending' },
    { id: 's2', name: 'Shipping Fleet Modernization', description: 'Build 50 modern cargo ships', budget_required: 6000, success_rate: 0.58, morale_impact: 2, efficiency_gain: 15, execution_month: 4, status: 'pending' },
    { id: 's3', name: 'Marine Safety Protocol', description: 'Strengthen maritime safety', budget_required: 1500, success_rate: 0.75, morale_impact: 2, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 's4', name: 'Inland Waterway Project', description: 'Develop 111 waterways', budget_required: 3000, success_rate: 0.55, morale_impact: 4, efficiency_gain: 11, execution_month: 3, status: 'pending' },
    { id: 's5', name: 'Container Terminal', description: 'Build automated terminals', budget_required: 5000, success_rate: 0.6, morale_impact: 1, efficiency_gain: 14, execution_month: 4, status: 'pending' },
    { id: 's6', name: 'Green Shipping Initiative', description: 'Promote low-emission vessels', budget_required: 2000, success_rate: 0.65, morale_impact: 3, efficiency_gain: 9, execution_month: 2, status: 'pending' },
  ],
  labour: [
    { id: 'l1', name: 'Wage Commission', description: 'Review minimum wages', budget_required: 1000, success_rate: 0.68, morale_impact: 12, efficiency_gain: 3, execution_month: 2, status: 'pending' },
    { id: 'l2', name: 'Labor Law Modernization', description: 'Update employment laws', budget_required: 1500, success_rate: 0.72, morale_impact: 8, efficiency_gain: 5, execution_month: 1, status: 'pending' },
    { id: 'l3', name: 'Skill Development Program', description: 'Train 5M workers', budget_required: 4000, success_rate: 0.65, morale_impact: 6, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'l4', name: 'Worker Safety Standards', description: 'Improve workplace safety', budget_required: 2000, success_rate: 0.74, morale_impact: 7, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'l5', name: 'Gig Economy Regulation', description: 'Create gig worker protections', budget_required: 1000, success_rate: 0.62, morale_impact: 9, efficiency_gain: 4, execution_month: 2, status: 'pending' },
    { id: 'l6', name: 'Social Security Expansion', description: 'Extend benefits to all workers', budget_required: 3000, success_rate: 0.6, morale_impact: 10, efficiency_gain: 2, execution_month: 3, status: 'pending' },
  ],
  social_justice: [
    { id: 'sj1', name: 'SC/ST Reservation', description: 'Strengthen quota system', budget_required: 2000, success_rate: 0.65, morale_impact: 6, efficiency_gain: 4, execution_month: 2, status: 'pending' },
    { id: 'sj2', name: 'Gender Equality Initiative', description: 'Women empowerment programs', budget_required: 2500, success_rate: 0.72, morale_impact: 8, efficiency_gain: 5, execution_month: 1, status: 'pending' },
    { id: 'sj3', name: 'Disability Rights', description: 'Support for persons with disabilities', budget_required: 1500, success_rate: 0.7, morale_impact: 7, efficiency_gain: 3, execution_month: 1, status: 'pending' },
    { id: 'sj4', name: 'Anti-Corruption Drive', description: 'Combat social corruption', budget_required: 2000, success_rate: 0.58, morale_impact: 4, efficiency_gain: 10, execution_month: 2, status: 'pending' },
    { id: 'sj5', name: 'Child Welfare Program', description: 'Protect children\'s rights', budget_required: 1500, success_rate: 0.75, morale_impact: 9, efficiency_gain: 2, execution_month: 1, status: 'pending' },
    { id: 'sj6', name: 'Minority Affairs', description: 'Support minority communities', budget_required: 2000, success_rate: 0.62, morale_impact: 5, efficiency_gain: 3, execution_month: 2, status: 'pending' },
  ],
  environment: [
    { id: 'en1', name: 'Forest Conservation', description: 'Protect 100M hectares', budget_required: 3000, success_rate: 0.62, morale_impact: 4, efficiency_gain: 8, execution_month: 3, status: 'pending' },
    { id: 'en2', name: 'Wildlife Protection', description: 'Save endangered species', budget_required: 2000, success_rate: 0.65, morale_impact: 5, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'en3', name: 'Plastic Ban Implementation', description: 'Eliminate single-use plastics', budget_required: 1500, success_rate: 0.6, morale_impact: 3, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'en4', name: 'Climate Action Plan', description: 'Carbon neutrality by 2070', budget_required: 5000, success_rate: 0.5, morale_impact: 2, efficiency_gain: 18, execution_month: 4, status: 'pending' },
    { id: 'en5', name: 'Waste Management System', description: 'Upgrade waste facilities', budget_required: 2500, success_rate: 0.68, morale_impact: 3, efficiency_gain: 9, execution_month: 2, status: 'pending' },
    { id: 'en6', name: 'Green City Initiative', description: 'Transform 50 cities green', budget_required: 4000, success_rate: 0.55, morale_impact: 4, efficiency_gain: 11, execution_month: 3, status: 'pending' },
  ],
  consumer_affairs: [
    { id: 'ca1', name: 'Quality Assurance', description: 'Strengthen product standards', budget_required: 1500, success_rate: 0.7, morale_impact: 4, efficiency_gain: 8, execution_month: 1, status: 'pending' },
    { id: 'ca2', name: 'Consumer Protection Law', description: 'Update consumer rights', budget_required: 1000, success_rate: 0.75, morale_impact: 5, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 'ca3', name: 'Fair Price Shop Network', description: 'Expand ration distribution', budget_required: 2000, success_rate: 0.68, morale_impact: 6, efficiency_gain: 5, execution_month: 2, status: 'pending' },
    { id: 'ca4', name: 'Food Safety Campaign', description: 'Improve food hygiene', budget_required: 1500, success_rate: 0.72, morale_impact: 4, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'ca5', name: 'E-commerce Regulation', description: 'Regulate online sales', budget_required: 1000, success_rate: 0.65, morale_impact: 2, efficiency_gain: 9, execution_month: 2, status: 'pending' },
    { id: 'ca6', name: 'Price Monitoring System', description: 'Real-time price tracking', budget_required: 1000, success_rate: 0.7, morale_impact: 3, efficiency_gain: 8, execution_month: 1, status: 'pending' },
  ],
  agriculture: [
    { id: 'ag1', name: 'Crop Insurance Scheme', description: 'Insure 100M farmers', budget_required: 3000, success_rate: 0.68, morale_impact: 8, efficiency_gain: 7, execution_month: 2, status: 'pending' },
    { id: 'ag2', name: 'Irrigation Expansion', description: 'Build 1000 dams/channels', budget_required: 4000, success_rate: 0.62, morale_impact: 5, efficiency_gain: 10, execution_month: 3, status: 'pending' },
    { id: 'ag3', name: 'Organic Farming Promotion', description: 'Convert 10M hectares organic', budget_required: 2500, success_rate: 0.58, morale_impact: 4, efficiency_gain: 8, execution_month: 3, status: 'pending' },
    { id: 'ag4', name: 'Seed Research Program', description: 'Develop high-yield seeds', budget_required: 2000, success_rate: 0.65, morale_impact: 3, efficiency_gain: 12, execution_month: 2, status: 'pending' },
    { id: 'ag5', name: 'Farmer Debt Relief', description: 'Waive farm loans', budget_required: 5000, success_rate: 0.72, morale_impact: 10, efficiency_gain: 2, execution_month: 1, status: 'pending' },
    { id: 'ag6', name: 'Agricultural Equipment', description: 'Subsidize farm machinery', budget_required: 3000, success_rate: 0.68, morale_impact: 7, efficiency_gain: 9, execution_month: 2, status: 'pending' },
  ],
  rural_development: [
    { id: 'rd1', name: 'MNREGA Implementation', description: 'Employ 100M rural workers', budget_required: 4000, success_rate: 0.65, morale_impact: 9, efficiency_gain: 4, execution_month: 2, status: 'pending' },
    { id: 'rd2', name: 'Rural Electrification', description: 'Connect 100K villages', budget_required: 3000, success_rate: 0.7, morale_impact: 7, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'rd3', name: 'Sanitation Drive', description: 'Build 50M toilets', budget_required: 2500, success_rate: 0.68, morale_impact: 6, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'rd4', name: 'Internet Connectivity', description: 'Connect villages via broadband', budget_required: 3000, success_rate: 0.62, morale_impact: 5, efficiency_gain: 11, execution_month: 2, status: 'pending' },
    { id: 'rd5', name: 'Housing Scheme', description: 'Build 50M rural homes', budget_required: 5000, success_rate: 0.58, morale_impact: 8, efficiency_gain: 5, execution_month: 3, status: 'pending' },
    { id: 'rd6', name: 'Cooperative Movement', description: 'Strengthen farmer cooperatives', budget_required: 2000, success_rate: 0.72, morale_impact: 6, efficiency_gain: 8, execution_month: 1, status: 'pending' },
  ],
};
