import { MinistryProgram } from './types';

export const MINISTRY_PROGRAMS: Record<string, MinistryProgram[]> = {
  defence: [
    { id: 'd1', name: 'Army Integration (1947)', description: 'Consolidate and re-equip armed forces post-partition.', budget_required: 12, success_rate: 0.85, morale_impact: 8, efficiency_gain: 5, execution_month: 0, status: 'pending' },
    { id: 'd2', name: 'NDA Khadakwasla Foundation', description: 'Establish the joint-services National Defence Academy.', budget_required: 8, success_rate: 0.8, morale_impact: 10, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'd3', name: 'DRDO Foundation (1958)', description: 'Establish the Defence Research and Development Organisation.', budget_required: 10, success_rate: 0.65, morale_impact: 5, efficiency_gain: 12, execution_month: 4, status: 'pending' },
    { id: 'd4', name: 'HAL Aircraft Assembly Plant', description: 'Upgrade domestic aircraft repair and assembly infrastructure.', budget_required: 7, success_rate: 0.7, morale_impact: 4, efficiency_gain: 8, execution_month: 3, status: 'pending' },
    { id: 'd5', name: 'Border Roads Development', description: 'Form the Border Roads Organisation to build strategic pathways.', budget_required: 6, success_rate: 0.75, morale_impact: 6, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'd6', name: 'Territorial Army Commission', description: 'Form a volunteer citizens army for secondary defense.', budget_required: 4, success_rate: 0.9, morale_impact: 6, efficiency_gain: 4, execution_month: 2, status: 'pending' },
  ],
  education: [
    { id: 'e1', name: 'Build IIT Kharagpur (1951)', description: 'Establish India\'s first Indian Institute of Technology.', budget_required: 10, success_rate: 0.75, morale_impact: 8, efficiency_gain: 15, execution_month: 1, status: 'pending' },
    { id: 'e2', name: 'National Literacy Campaign', description: 'Deploy adult literacy drives to lift rates from the 12% baseline.', budget_required: 6, success_rate: 0.7, morale_impact: 6, efficiency_gain: 10, execution_month: 3, status: 'pending' },
    { id: 'e3', name: 'Primary School Drive', description: 'Construct basic primary schools in rural panchayats.', budget_required: 8, success_rate: 0.8, morale_impact: 7, efficiency_gain: 8, execution_month: 6, status: 'pending' },
    { id: 'e4', name: 'Establish UGC (1956)', description: 'Found the University Grants Commission to supervise universities.', budget_required: 4, success_rate: 0.85, morale_impact: 5, efficiency_gain: 9, execution_month: 2, status: 'pending' },
    { id: 'e5', name: 'Sanskrit & Heritage Centers', description: 'Preserve classical education and historical academies.', budget_required: 3, success_rate: 0.9, morale_impact: 8, efficiency_gain: 3, execution_month: 0, status: 'pending' },
    { id: 'e6', name: 'Science Labs Endowment', description: 'Equip national universities with modern science laboratories.', budget_required: 7, success_rate: 0.65, morale_impact: 6, efficiency_gain: 12, execution_month: 5, status: 'pending' },
  ],
  health: [
    { id: 'h1', name: 'Build AIIMS New Delhi (1956)', description: 'Establish the flagship hospital and medical research center.', budget_required: 12, success_rate: 0.8, morale_impact: 10, efficiency_gain: 15, execution_month: 1, status: 'pending' },
    { id: 'h2', name: 'Malaria Control Campaign', description: 'Launch massive DDT spraying and anti-malaria programs.', budget_required: 5, success_rate: 0.75, morale_impact: 7, efficiency_gain: 8, execution_month: 4, status: 'pending' },
    { id: 'h3', name: 'Primary Health Centres (PHC)', description: 'Establish block-level health centers across rural India.', budget_required: 8, success_rate: 0.7, morale_impact: 6, efficiency_gain: 10, execution_month: 2, status: 'pending' },
    { id: 'h4', name: 'Smallpox Vaccination Drive', description: 'National inoculation campaign to contain smallpox outbreaks.', budget_required: 6, success_rate: 0.85, morale_impact: 8, efficiency_gain: 9, execution_month: 3, status: 'pending' },
    { id: 'h5', name: 'Maternal Care & Midwifery', description: 'Train community nurses to combat high infant mortality rates.', budget_required: 4, success_rate: 0.8, morale_impact: 7, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 'h6', name: 'BCG Tuberculosis Campaign', description: 'Roll out the BCG vaccine to curb tuberculosis transmission.', budget_required: 5, success_rate: 0.72, morale_impact: 5, efficiency_gain: 7, execution_month: 2, status: 'pending' },
  ],
  finance: [
    { id: 'f1', name: '1st Five-Year Plan (1951)', description: 'Draft the agrarian and industrial planning blueprint.', budget_required: 15, success_rate: 0.75, morale_impact: 5, efficiency_gain: 20, execution_month: 0, status: 'pending' },
    { id: 'f2', name: 'RBI Nationalisation (1949)', description: 'Bring the Reserve Bank of India under full government ownership.', budget_required: 5, success_rate: 0.9, morale_impact: 3, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'f3', name: 'Imperial Bank Transition', description: 'Nationalize and transition the Imperial Bank to SBI.', budget_required: 6, success_rate: 0.85, morale_impact: 4, efficiency_gain: 15, execution_month: 1, status: 'pending' },
    { id: 'f4', name: 'Revenue & Customs Audit', description: 'Establish independent revenue services to plug leaks.', budget_required: 3, success_rate: 0.78, morale_impact: -2, efficiency_gain: 10, execution_month: 2, status: 'pending' },
    { id: 'f5', name: 'Inflation & Currency Peg', description: 'Peg the Indian Rupee to the Sterling to maintain trade values.', budget_required: 4, success_rate: 0.7, morale_impact: 2, efficiency_gain: 8, execution_month: 1, status: 'pending' },
    { id: 'f6', name: 'LIC Establishment (1956)', description: 'Nationalize and merge private insurers into Life Insurance Corp.', budget_required: 10, success_rate: 0.8, morale_impact: 5, efficiency_gain: 14, execution_month: 2, status: 'pending' },
  ],
  commerce: [
    { id: 'c1', name: 'State Trading Corp', description: 'Establish STC to export primary commodities (tea, jute).', budget_required: 7, success_rate: 0.72, morale_impact: 5, efficiency_gain: 10, execution_month: 1, status: 'pending' },
    { id: 'c2', name: 'Trade Agreements with UK/US', description: 'Negotiate favorable tariffs for post-independence exports.', budget_required: 3, success_rate: 0.68, morale_impact: 4, efficiency_gain: 12, execution_month: 2, status: 'pending' },
    { id: 'c3', name: 'Small Scale Industries Board', description: 'Subsidize handlooms, Khadi, and cottage industries.', budget_required: 6, success_rate: 0.8, morale_impact: 8, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 'c4', name: 'Logistics Warehousing', description: 'Build state grain and cotton godowns for reserve storage.', budget_required: 8, success_rate: 0.65, morale_impact: 3, efficiency_gain: 9, execution_month: 4, status: 'pending' },
    { id: 'c5', name: 'Patents and Trademarks Act', description: 'Establish the intellectual property rules of the new republic.', budget_required: 2, success_rate: 0.85, morale_impact: 2, efficiency_gain: 7, execution_month: 2, status: 'pending' },
    { id: 'c6', name: 'Essential Commodities Act', description: 'Control prices and distribution of food grains and oils.', budget_required: 4, success_rate: 0.75, morale_impact: 6, efficiency_gain: 8, execution_month: 1, status: 'pending' },
  ],
  it: [
    { id: 'i1', name: 'Establish TIFR (1945/1947)', description: 'Fund the Tata Institute of Fundamental Research.', budget_required: 8, success_rate: 0.85, morale_impact: 6, efficiency_gain: 15, execution_month: 3, status: 'pending' },
    { id: 'i2', name: 'Atomic Energy Commission', description: 'Create the AEC under Homi Bhabha for research.', budget_required: 10, success_rate: 0.7, morale_impact: 5, efficiency_gain: 18, execution_month: 5, status: 'pending' },
    { id: 'i3', name: 'CSIR National Laboratories', description: 'Establish a network of national scientific research labs.', budget_required: 9, success_rate: 0.8, morale_impact: 4, efficiency_gain: 12, execution_month: 2, status: 'pending' },
    { id: 'i4', name: 'Electronic & Radio Labs', description: 'Fund research into state-owned radio and telegram circuits.', budget_required: 5, success_rate: 0.72, morale_impact: 3, efficiency_gain: 10, execution_month: 8, status: 'pending' },
    { id: 'i5', name: 'Geological Survey Expansion', description: 'Map India\'s mineral and oil reserves with scientific surveys.', budget_required: 6, success_rate: 0.75, morale_impact: 4, efficiency_gain: 8, execution_month: 1, status: 'pending' },
    { id: 'i6', name: 'Mathematical Science Grant', description: 'Fund fellowships and post-graduate studies in science.', budget_required: 4, success_rate: 0.82, morale_impact: 5, efficiency_gain: 6, execution_month: 3, status: 'pending' },
  ],
  power: [
    { id: 'p1', name: 'Bhakra Nangal Dam (Power)', description: 'Construct the mega hydroelectric project in Punjab.', budget_required: 15, success_rate: 0.65, morale_impact: 10, efficiency_gain: 25, execution_month: 4, status: 'pending' },
    { id: 'p2', name: 'Grid Integration Act', description: 'Incorporate regional power boards into state grids.', budget_required: 8, success_rate: 0.75, morale_impact: 3, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'p3', name: 'Damodar Valley Project', description: 'Harness the Damodar river for thermal and hydro power.', budget_required: 12, success_rate: 0.7, morale_impact: 7, efficiency_gain: 18, execution_month: 3, status: 'pending' },
    { id: 'p4', name: 'Rural Electrification Pilot', description: 'Electrify 500 villages in selected agrarian zones.', budget_required: 5, success_rate: 0.8, morale_impact: 8, efficiency_gain: 6, execution_month: 4, status: 'pending' },
    { id: 'p5', name: 'Coal Thermal Station', description: 'Build India\'s first modern coal thermal station at Bokaro.', budget_required: 10, success_rate: 0.72, morale_impact: 4, efficiency_gain: 15, execution_month: 3, status: 'pending' },
    { id: 'p6', name: 'Hydro Feasibility Surveys', description: 'Map Himalayan rivers for potential future dam projects.', budget_required: 3, success_rate: 0.85, morale_impact: 3, efficiency_gain: 5, execution_month: 2, status: 'pending' },
  ],
  water: [
    { id: 'w1', name: 'Canal Network Construction', description: 'Build agricultural canal networks in Punjab and Haryana.', budget_required: 10, success_rate: 0.7, morale_impact: 8, efficiency_gain: 15, execution_month: 4, status: 'pending' },
    { id: 'w2', name: 'Tube-well Subsidies', description: 'Finance drilling of tube-wells for irrigation.', budget_required: 5, success_rate: 0.8, morale_impact: 7, efficiency_gain: 10, execution_month: 2, status: 'pending' },
    { id: 'w3', name: 'Drinking Water Wells', description: 'Drill community drinking wells in drought-prone villages.', budget_required: 4, success_rate: 0.85, morale_impact: 10, efficiency_gain: 6, execution_month: 3, status: 'pending' },
    { id: 'w4', name: 'Flood Control Bunds', description: 'Build earthen embankments along Kosi and Brahmaputra.', budget_required: 7, success_rate: 0.6, morale_impact: 5, efficiency_gain: 8, execution_month: 4, status: 'pending' },
    { id: 'w5', name: 'Hirakud Dam Construction', description: 'Construct the longest earthen dam in Orissa for water management.', budget_required: 12, success_rate: 0.68, morale_impact: 6, efficiency_gain: 16, execution_month: 1, status: 'pending' },
    { id: 'w6', name: 'Rainwater Storage Tanks', description: 'Restore stepwells and traditional tanks in Rajasthan.', budget_required: 3, success_rate: 0.9, morale_impact: 7, efficiency_gain: 5, execution_month: 5, status: 'pending' },
  ],
  railways: [
    { id: 'r1', name: 'Nationalize Railways (1951)', description: 'Consolidate 37 private lines into single Indian Railways.', budget_required: 14, success_rate: 0.85, morale_impact: 8, efficiency_gain: 20, execution_month: 6, status: 'pending' },
    { id: 'r2', name: 'Chittaranjan Locomotive', description: 'Build steam locomotive manufacturing facility at Chittaranjan.', budget_required: 10, success_rate: 0.75, morale_impact: 6, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'r3', name: 'Track Gauge Standardization', description: 'Standardize broad gauge tracks on major arterial routes.', budget_required: 8, success_rate: 0.7, morale_impact: 4, efficiency_gain: 10, execution_month: 4, status: 'pending' },
    { id: 'r4', name: 'Integral Coach Factory (ICF)', description: 'Establish passenger coach factory at Perambur.', budget_required: 9, success_rate: 0.8, morale_impact: 5, efficiency_gain: 11, execution_month: 2, status: 'pending' },
    { id: 'r5', name: 'Bridge Reconstruction', description: 'Restore railway bridges damaged during Partition.', budget_required: 6, success_rate: 0.78, morale_impact: 4, efficiency_gain: 8, execution_month: 3, status: 'pending' },
    { id: 'r6', name: 'Third Class Passenger Perks', description: 'Add toilets, fans, and basic seating to third-class coaches.', budget_required: 4, success_rate: 0.9, morale_impact: 12, efficiency_gain: 3, execution_month: 1, status: 'pending' },
  ],
  roads: [
    { id: 'rd1', name: 'National Highways Act (1956)', description: 'Codify and fund the national highway network.', budget_required: 12, success_rate: 0.8, morale_impact: 6, efficiency_gain: 16, execution_month: 5, status: 'pending' },
    { id: 'rd2', name: 'District Road Metalling', description: 'Convert mud roads in districts into metalled/tarmac roads.', budget_required: 7, success_rate: 0.75, morale_impact: 5, efficiency_gain: 8, execution_month: 4, status: 'pending' },
    { id: 'rd3', name: 'State Transport Corporation', description: 'Found state bus services to connect towns and rural areas.', budget_required: 6, success_rate: 0.82, morale_impact: 8, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'rd4', name: 'Grand Trunk Road Repair', description: 'Resurface and widen the historic Grand Trunk Road.', budget_required: 8, success_rate: 0.7, morale_impact: 4, efficiency_gain: 10, execution_month: 3, status: 'pending' },
    { id: 'rd5', name: 'Bullock Cart Modernisation', description: 'Standardize rubber tires on bullock carts to protect roads.', budget_required: 2, success_rate: 0.9, morale_impact: 7, efficiency_gain: 3, execution_month: 2, status: 'pending' },
    { id: 'rd6', name: 'Bridges & Culverts Build', description: 'Construct concrete culverts to prevent monsoon washouts.', budget_required: 5, success_rate: 0.85, morale_impact: 4, efficiency_gain: 6, execution_month: 2, status: 'pending' },
  ],
  aviation: [
    { id: 'av1', name: 'Air India Nationalisation', description: 'Acquire and nationalize Air India (1953) for flag operations.', budget_required: 10, success_rate: 0.85, morale_impact: 7, efficiency_gain: 12, execution_month: 3, status: 'pending' },
    { id: 'av2', name: 'Santa Cruz & Dum Dum Airport', description: 'Upgrade Bombay and Calcutta airports to handle heavy piston planes.', budget_required: 7, success_rate: 0.72, morale_impact: 4, efficiency_gain: 9, execution_month: 1, status: 'pending' },
    { id: 'av3', name: 'Civil Aviation Directorate', description: 'Establish safety, license, and airspace codes.', budget_required: 2, success_rate: 0.85, morale_impact: 1, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 'av4', name: 'Aviation Pilot School', description: 'Establish a national academy to train civilian pilots.', budget_required: 4, success_rate: 0.78, morale_impact: 4, efficiency_gain: 5, execution_month: 2, status: 'pending' },
    { id: 'av5', name: 'Postal Air Mail Expansion', description: 'Run night airmail services to expedite nationwide sorting.', budget_required: 5, success_rate: 0.8, morale_impact: 5, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'av6', name: 'Radio Navigation Towers', description: 'Install radio direction finders at major aerodromes.', budget_required: 3, success_rate: 0.7, morale_impact: 2, efficiency_gain: 7, execution_month: 4, status: 'pending' },
  ],
  shipping: [
    { id: 's1', name: 'Vizag Shipyard Expansion', description: 'Expand India\'s first national shipyard at Visakhapatnam.', budget_required: 10, success_rate: 0.72, morale_impact: 6, efficiency_gain: 14, execution_month: 3, status: 'pending' },
    { id: 's2', name: 'Kandla Port Development', description: 'Build Kandla port as a major gateway post-loss of Karachi.', budget_required: 12, success_rate: 0.8, morale_impact: 8, efficiency_gain: 18, execution_month: 4, status: 'pending' },
    { id: 's3', name: 'Lighthouse Modernization', description: 'Upgrade lighthouses with electrical beacons for safe shipping.', budget_required: 3, success_rate: 0.85, morale_impact: 3, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 's4', name: 'Inland Shipping Channels', description: 'Dredge Ganga and Hooghly for commercial barge shipping.', budget_required: 7, success_rate: 0.65, morale_impact: 4, efficiency_gain: 9, execution_month: 3, status: 'pending' },
    { id: 's5', name: 'Eastern Shipping Corp', description: 'Found a state shipping line to handle regional cargo.', budget_required: 8, success_rate: 0.75, morale_impact: 5, efficiency_gain: 11, execution_month: 4, status: 'pending' },
    { id: 's6', name: 'Port Trust Reorganization', description: 'Standardize operations at Bombay, Calcutta, and Madras ports.', budget_required: 4, success_rate: 0.85, morale_impact: 3, efficiency_gain: 7, execution_month: 2, status: 'pending' },
  ],
  labour: [
    { id: 'l1', name: 'Minimum Wages Act (1948)', description: 'Statutory minimum wage framework for scheduled employments.', budget_required: 4, success_rate: 0.85, morale_impact: 15, efficiency_gain: 4, execution_month: 2, status: 'pending' },
    { id: 'l2', name: 'Factories Act 1948', description: 'Enforce 48-hour workweeks, safety, and child labor prohibitions.', budget_required: 3, success_rate: 0.8, morale_impact: 10, efficiency_gain: 6, execution_month: 1, status: 'pending' },
    { id: 'l3', name: 'Industrial Disputes Act', description: 'Create industrial tribunals for mediation between unions & owners.', budget_required: 3, success_rate: 0.78, morale_impact: 8, efficiency_gain: 5, execution_month: 3, status: 'pending' },
    { id: 'l4', name: 'Employ State Insurance (ESI)', description: 'Introduce state healthcare and maternity insurance for workers.', budget_required: 8, success_rate: 0.72, morale_impact: 12, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'l5', name: 'Provident Fund Scheme', description: 'Establish retirement provident funds for industrial workers.', budget_required: 6, success_rate: 0.8, morale_impact: 10, efficiency_gain: 5, execution_month: 2, status: 'pending' },
    { id: 'l6', name: 'Employment Exchanges', description: 'Set up local job centers to register and place unemployed youth.', budget_required: 2, success_rate: 0.88, morale_impact: 7, efficiency_gain: 7, execution_month: 3, status: 'pending' },
  ],
  social_justice: [
    { id: 'sj1', name: 'Untouchability Abolition', description: 'Enforce Article 17 of the constitution to abolish untouchability.', budget_required: 5, success_rate: 0.72, morale_impact: 12, efficiency_gain: 5, execution_month: 2, status: 'pending' },
    { id: 'sj2', name: 'Tribal Welfare Board', description: 'Form commission to protect scheduled tribes and forest rights.', budget_required: 4, success_rate: 0.75, morale_impact: 8, efficiency_gain: 4, execution_month: 1, status: 'pending' },
    { id: 'sj3', name: 'First OBC Commission', description: 'Form the Kaka Kalelkar Commission to assess backward classes.', budget_required: 3, success_rate: 0.85, morale_impact: 6, efficiency_gain: 3, execution_month: 1, status: 'pending' },
    { id: 'sj4', name: 'Harijan Education Grants', description: 'Finance boarding schools and textbooks for SC/ST children.', budget_required: 6, success_rate: 0.8, morale_impact: 10, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'sj5', name: 'Orphanage & Shelter Homes', description: 'Establish public shelters for destitute widows and orphans.', budget_required: 4, success_rate: 0.82, morale_impact: 8, efficiency_gain: 4, execution_month: 1, status: 'pending' },
    { id: 'sj6', name: 'Vocational Rehab Centers', description: 'Set up craft training centers for disabled war veterans.', budget_required: 3, success_rate: 0.88, morale_impact: 7, efficiency_gain: 5, execution_month: 2, status: 'pending' },
  ],
  environment: [
    { id: 'en1', name: 'Forest Conservation Code', description: 'Revise imperial forest rules to expand village reserves.', budget_required: 5, success_rate: 0.7, morale_impact: 4, efficiency_gain: 6, execution_month: 3, status: 'pending' },
    { id: 'en2', name: 'Indian Forest Act Audit', description: 'Appoint forest wardens to curb wood smuggling and poaching.', budget_required: 4, success_rate: 0.75, morale_impact: 3, efficiency_gain: 5, execution_month: 2, status: 'pending' },
    { id: 'en3', name: 'Gir Lion Sanctuary Support', description: 'Establish conservation support for the remaining Asiatic Lions.', budget_required: 3, success_rate: 0.8, morale_impact: 6, efficiency_gain: 4, execution_month: 1, status: 'pending' },
    { id: 'en4', name: 'River Flow Monitoring', description: 'Establish hydrological stations to measure silt and flow rates.', budget_required: 5, success_rate: 0.72, morale_impact: 2, efficiency_gain: 7, execution_month: 4, status: 'pending' },
    { id: 'en5', name: 'Soil Conservation Board', description: 'Run programs to prevent soil erosion in drylands.', budget_required: 6, success_rate: 0.68, morale_impact: 4, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'en6', name: 'Public Health Sanitation', description: 'Fund municipal sanitation guidelines in major towns.', budget_required: 4, success_rate: 0.8, morale_impact: 5, efficiency_gain: 6, execution_month: 3, status: 'pending' },
  ],
  consumer_affairs: [
    { id: 'ca1', name: 'Agmark Standard Label', description: 'Enforce quality certificates on ghee, oils, and butter.', budget_required: 3, success_rate: 0.8, morale_impact: 5, efficiency_gain: 7, execution_month: 1, status: 'pending' },
    { id: 'ca2', name: 'Standard Weights Act', description: 'Abolish regional weighing units and standardize metric scales.', budget_required: 4, success_rate: 0.85, morale_impact: 6, efficiency_gain: 10, execution_month: 1, status: 'pending' },
    { id: 'ca3', name: 'Ration Card Expansion', description: 'Introduce ration cards to protect poor from high grain prices.', budget_required: 6, success_rate: 0.75, morale_impact: 12, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'ca4', name: 'Anti-Adulteration Laws', description: 'Imprison traders adulterating essential milk, flour, and spices.', budget_required: 5, success_rate: 0.72, morale_impact: 8, efficiency_gain: 9, execution_month: 1, status: 'pending' },
    { id: 'ca5', name: 'Public Grain Stocks Control', description: 'Establish state-run buffer depots to combat hoarding.', budget_required: 7, success_rate: 0.7, morale_impact: 7, efficiency_gain: 8, execution_month: 2, status: 'pending' },
    { id: 'ca6', name: 'Local Price Courts', description: 'Empower district officers to regulate maximum retail prices.', budget_required: 2, success_rate: 0.78, morale_impact: 6, efficiency_gain: 5, execution_month: 1, status: 'pending' },
  ],
  agriculture: [
    { id: 'ag1', name: 'Zamindari Abolition Act', description: 'Redistribute land from landlords to actual farmers.', budget_required: 15, success_rate: 0.65, morale_impact: 14, efficiency_gain: 18, execution_month: 2, status: 'pending' },
    { id: 'ag2', name: 'Land Mortgage Banks', description: 'Provide credit to cooperative farm credit societies.', budget_required: 8, success_rate: 0.75, morale_impact: 8, efficiency_gain: 10, execution_month: 3, status: 'pending' },
    { id: 'ag3', name: 'Compost & Organic Drive', description: 'Promote green manuring and compost pits in villages.', budget_required: 4, success_rate: 0.85, morale_impact: 5, efficiency_gain: 6, execution_month: 3, status: 'pending' },
    { id: 'ag4', name: 'High-Yield Wheat Trials', description: 'Import and test improved crop seeds in state farms.', budget_required: 6, success_rate: 0.72, morale_impact: 4, efficiency_gain: 12, execution_month: 2, status: 'pending' },
    { id: 'ag5', name: 'Farmer Cooperative Dairy', description: 'Support local co-op milk collection (Amul foundations).', budget_required: 10, success_rate: 0.82, morale_impact: 10, efficiency_gain: 14, execution_month: 1, status: 'pending' },
    { id: 'ag6', name: 'Tractor Subsidies', description: 'Provide loans to agrarian cooperatives to buy tractors.', budget_required: 7, success_rate: 0.7, morale_impact: 6, efficiency_gain: 9, execution_month: 2, status: 'pending' },
  ],
  rural_development: [
    { id: 'rd1', name: 'Community Dev Program', description: 'First major village self-help program (CDP 1952).', budget_required: 12, success_rate: 0.72, morale_impact: 10, efficiency_gain: 15, execution_month: 2, status: 'pending' },
    { id: 'rd2', name: 'Panchayati Raj Integration', description: 'Establish administrative powers for village panchayats.', budget_required: 8, success_rate: 0.8, morale_impact: 9, efficiency_gain: 10, execution_month: 2, status: 'pending' },
    { id: 'rd3', name: 'Khadi & Village Commission', description: 'Develop rural cottage industries (pottery, handspinning).', budget_required: 6, success_rate: 0.85, morale_impact: 8, efficiency_gain: 6, execution_month: 2, status: 'pending' },
    { id: 'rd4', name: 'Rural Water Well Network', description: 'Finance ringed community wells in every panchayat.', budget_required: 5, success_rate: 0.82, morale_impact: 9, efficiency_gain: 7, execution_month: 2, status: 'pending' },
    { id: 'rd5', name: 'Gram Udyog Training', description: 'Vocational training in blacksmithing, carpentry, and weaving.', budget_required: 4, success_rate: 0.88, morale_impact: 7, efficiency_gain: 8, execution_month: 3, status: 'pending' },
    { id: 'rd6', name: 'Rural Road Connectivity', description: 'Connect remote villages to state highways via dirt tracks.', budget_required: 10, success_rate: 0.65, morale_impact: 8, efficiency_gain: 11, execution_month: 1, status: 'pending' },
  ],
};
