import { ResearchTech } from './types';

export const RESEARCH_TECHS: ResearchTech[] = [
  // Economy & Infrastructure (Category: 'economy')
  {
    id: 'five_year_plan',
    category: 'economy',
    name: 'First Five-Year Plan Draft',
    cost_rp: 200,
    cost_budget: 15,
    desc: 'Plan coordinated industrial growth. Permanent GDP expansion and enhanced tax collection index.',
    effect: 'GDP +0.5T, Tax Collection +5%',
    x: 1,
    y: 2,
  },
  {
    id: 'rbi_national',
    category: 'economy',
    name: 'Reserve Bank Nationalisation',
    cost_rp: 140,
    cost_budget: 6,
    desc: 'Bring the central bank under state control. Boosts Finance efficiency & national Tax Collection.',
    effect: 'Finance Efficiency +10%, Tax Collection +4%',
    prerequisites: ['five_year_plan'],
    x: 2,
    y: 1,
  },
  {
    id: 'tariff_protection',
    category: 'economy',
    name: 'Tariff Protection Act',
    cost_rp: 130,
    cost_budget: 5,
    desc: 'Protect infant domestic manufacturing. Boosts Commerce ministry efficiency and raises national GDP.',
    effect: 'Commerce Efficiency +8%, GDP +0.2T',
    prerequisites: ['rbi_national'],
    x: 3,
    y: 1,
  },
  {
    id: 'bhakra_dam',
    category: 'economy',
    name: 'Bhakra Nangal Hydro Grid',
    cost_rp: 180,
    cost_budget: 10,
    desc: 'Construct a massive multipurpose river valley project. Boosts national Infrastructure index & Power efficiency.',
    effect: 'Infrastructure +4%, Power Efficiency +8%',
    prerequisites: ['five_year_plan'],
    x: 2,
    y: 2,
  },
  {
    id: 'chittaranjan_loco',
    category: 'economy',
    name: 'Chittaranjan Loco Works',
    cost_rp: 160,
    cost_budget: 8,
    desc: 'Establish domestic steam locomotive production. Boosts Infrastructure index & Railways efficiency.',
    effect: 'Infrastructure +4%, Railways Efficiency +10%',
    prerequisites: ['bhakra_dam'],
    x: 3,
    y: 2,
  },
  {
    id: 'national_highway',
    category: 'economy',
    name: 'National Highway Framework',
    cost_rp: 140,
    cost_budget: 6,
    desc: 'Formulate road links across industrial centers. Boosts national Infrastructure index & Road Transport efficiency.',
    effect: 'Infrastructure +3%, Road Transport Efficiency +8%',
    prerequisites: ['five_year_plan'],
    x: 2,
    y: 3,
  },

  // Defence & Shipping (Category: 'defence')
  {
    id: 'ncc_setup',
    category: 'defence',
    name: 'National Cadet Corps Setup',
    cost_rp: 120,
    cost_budget: 4,
    desc: 'Establish youth military training wings. Boosts Defence morale and staffing rates.',
    effect: 'Defence Morale +5%, Defence Staffing +15%',
    x: 1,
    y: 2,
  },
  {
    id: 'hal_setup',
    category: 'defence',
    name: 'Hindustan Aircraft Factory',
    cost_rp: 150,
    cost_budget: 8,
    desc: 'Build military aircraft locally. Boosts Defence ministry morale and operational efficiency.',
    effect: 'Defence Efficiency +10%, Defence Morale +8%',
    prerequisites: ['ncc_setup'],
    x: 2,
    y: 1,
  },
  {
    id: 'air_india_nat',
    category: 'defence',
    name: 'Air India Nationalisation',
    cost_rp: 130,
    cost_budget: 5,
    desc: 'Consolidate domestic airlines into a national carrier. Boosts Aviation efficiency.',
    effect: 'Aviation Efficiency +10%, Aviation Morale +5%',
    prerequisites: ['hal_setup'],
    x: 3,
    y: 1,
  },
  {
    id: 'scindia_steam',
    category: 'defence',
    name: 'Scindia Steam Navigation',
    cost_rp: 140,
    cost_budget: 6,
    desc: 'Expand cargo shipping fleets. Boosts Shipping efficiency and national trade volume.',
    effect: 'Shipping Efficiency +10%, Trade Volume +₹1.2B',
    prerequisites: ['ncc_setup'],
    x: 2,
    y: 3,
  },

  // Social Welfare & Labs (Category: 'social')
  {
    id: 'iit_setup',
    category: 'social',
    name: 'Establish IIT Network',
    cost_rp: 100,
    cost_budget: 5,
    desc: 'Establish Indian Institutes of Technology. +2% Literacy rate and +5% success rate to all Education programs.',
    effect: 'Literacy +2%, Education Success Rate +5%',
    x: 1,
    y: 1.5,
  },
  {
    id: 'tifr_labs',
    category: 'social',
    name: 'Tata Institute of Research',
    cost_rp: 160,
    cost_budget: 8,
    desc: 'Pioneer physical & nuclear research. IT programs execute 20% faster and IT efficiency rises by 12%.',
    effect: 'IT Efficiency +12%, IT Program Speed +20%',
    prerequisites: ['iit_setup'],
    x: 2,
    y: 1,
  },
  {
    id: 'sindri_fertilizer',
    category: 'social',
    name: 'Sindri Fertilizer Factory',
    cost_rp: 170,
    cost_budget: 9,
    desc: 'Launch state-owned chemical fertilizer production. Agriculture efficiency rises +12%, NLEC feed production +50M kg.',
    effect: 'Agriculture Efficiency +12%, NLEC Feed Production +50M kg/month',
    prerequisites: ['tifr_labs'],
    x: 3,
    y: 1,
  },
  {
    id: 'aiims_setup',
    category: 'social',
    name: 'Establish AIIMS Network',
    cost_rp: 120,
    cost_budget: 6,
    desc: 'Launch All India Institute of Medical Sciences. +3% Healthcare Index and +5% success rate to Health programs.',
    effect: 'Healthcare Index +3%, Health Success Rate +5%',
    prerequisites: ['iit_setup'],
    x: 2,
    y: 2,
  },
  {
    id: 'damodar_valley',
    category: 'social',
    name: 'Damodar Valley Grid',
    cost_rp: 150,
    cost_budget: 7,
    desc: 'Supply water canals and prevent floods. Boosts Agriculture yields and Water Resources efficiency.',
    effect: 'Water Resources Efficiency +10%, Agriculture Morale +5%',
    prerequisites: ['aiims_setup'],
    x: 3,
    y: 2,
  },
  {
    id: 'min_wages_act',
    category: 'social',
    name: 'Minimum Wages Legislation',
    cost_rp: 100,
    cost_budget: 3,
    desc: 'Enforce statutory minimum wages. Boosts Labour ministry morale and operational efficiency.',
    effect: 'Labour Morale +15%, Labour Efficiency +5%',
    x: 1,
    y: 4,
  },
  {
    id: 'tribal_welfare',
    category: 'social',
    name: 'Tribal Welfare Allocations',
    cost_rp: 110,
    cost_budget: 4,
    desc: 'Apportion welfare funds for tribal and backward communities. Boosts Social Justice morale & efficiency.',
    effect: 'Social Justice Morale +15%, Efficiency +6%',
    prerequisites: ['min_wages_act'],
    x: 2,
    y: 3,
  },
  {
    id: 'forest_reserve',
    category: 'social',
    name: 'Forest Protection Act',
    cost_rp: 100,
    cost_budget: 3,
    desc: 'Regulate logging and establish national parks. Boosts Environment morale and efficiency.',
    effect: 'Environment Morale +10%, Efficiency +8%',
    prerequisites: ['min_wages_act'],
    x: 2,
    y: 4,
  },
  {
    id: 'essential_supplies',
    category: 'social',
    name: 'Essential Supplies Act',
    cost_rp: 100,
    cost_budget: 4,
    desc: 'Regulate trade in essential consumer items. Boosts Consumer Affairs efficiency and morale.',
    effect: 'Consumer Affairs Efficiency +10%, Morale +5%',
    prerequisites: ['forest_reserve'],
    x: 3,
    y: 4,
  },
  {
    id: 'community_dev',
    category: 'social',
    name: 'Community Development',
    cost_rp: 150,
    cost_budget: 8,
    desc: 'Launch village self-reliance programs. Boosts Rural Development morale and efficiency.',
    effect: 'Rural Development Morale +12%, Efficiency +8%',
    prerequisites: ['min_wages_act'],
    x: 2,
    y: 5,
  },
];
